CREATE TABLE IF NOT EXISTS users (
         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
         name VARCHAR(255) NOT NULL,
         email VARCHAR(512) NOT NULL UNIQUE,
         CONSTRAINT pk_user PRIMARY KEY (id),
         CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
       );

--       CREATE TABLE IF NOT EXISTS items (
--         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--         name VARCHAR(255),
--         description VARCHAR(4000),
--         available BOOLEAN,
--         owner_id BIGINT NOT NULL,
--         CONSTRAINT pk_item PRIMARY KEY (id),
--         CONSTRAINT FK_ITEM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id),
--         CONSTRAINT UQ_OWNER_ITEM_NAME UNIQUE(owner_id, name)
--       );